-- Debezium(LogMiner) 전용 CDC 계정 생성 및 권한 부여.
-- 주의: gvenzl/oracle-xe 이미지의 init 훅은 .env 값을 SQL로 치환해주지 않으므로,
-- 아래 계정/비밀번호는 .env.example 의 ORACLE_CDC_USER / ORACLE_CDC_USER_PASSWORD 와
-- 반드시 동일하게 유지하세요. 값을 바꾸려면 이 파일도 함께 수정해야 합니다.

ALTER SESSION SET CONTAINER = CDB$ROOT;

CREATE USER "C##DBZUSER" IDENTIFIED BY "ChangeMe_Cdc_2026!"
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  CONTAINER = ALL;

GRANT CREATE SESSION           TO "C##DBZUSER" CONTAINER = ALL;
GRANT SET CONTAINER            TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$DATABASE    TO "C##DBZUSER" CONTAINER = ALL;
GRANT FLASHBACK ANY TABLE      TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ANY TABLE         TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT_CATALOG_ROLE      TO "C##DBZUSER" CONTAINER = ALL;
GRANT EXECUTE_CATALOG_ROLE     TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ANY TRANSACTION   TO "C##DBZUSER" CONTAINER = ALL;
GRANT LOGMINING                TO "C##DBZUSER" CONTAINER = ALL;

GRANT CREATE TABLE             TO "C##DBZUSER" CONTAINER = ALL;
GRANT LOCK ANY TABLE           TO "C##DBZUSER" CONTAINER = ALL;
GRANT ALTER ANY TABLE          TO "C##DBZUSER" CONTAINER = ALL;
GRANT CREATE SEQUENCE          TO "C##DBZUSER" CONTAINER = ALL;

GRANT EXECUTE ON DBMS_LOGMNR   TO "C##DBZUSER" CONTAINER = ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO "C##DBZUSER" CONTAINER = ALL;

GRANT SELECT ON V_$LOG                  TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$LOG_HISTORY          TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_LOGS          TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS      TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS    TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$LOGFILE              TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$ARCHIVED_LOG         TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS  TO "C##DBZUSER" CONTAINER = ALL;
GRANT SELECT ON V_$TRANSACTION          TO "C##DBZUSER" CONTAINER = ALL;
