-- ETL 컬럼 매핑 수식 도움말.
--
-- 화면 문구와 예제는 배포 파일에 박지 않고 메타DB에서 관리한다. 새 함수가 필요하면
-- 이 테이블에 행을 추가하면 되고, 프론트는 API 응답만 그린다.
CREATE TABLE etl_formula_help (
    id            BIGSERIAL PRIMARY KEY,
    function_name VARCHAR(80)  NOT NULL,
    category      VARCHAR(40)  NOT NULL,
    syntax        VARCHAR(300) NOT NULL,
    summary       TEXT         NOT NULL,
    usage_text    TEXT         NOT NULL,
    examples_json TEXT         NOT NULL DEFAULT '[]',
    notice        TEXT,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    enabled       BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_etl_formula_help_name ON etl_formula_help (lower(function_name));
CREATE INDEX idx_etl_formula_help_category ON etl_formula_help (category, sort_order, function_name);
CREATE INDEX idx_etl_formula_help_enabled ON etl_formula_help (enabled) WHERE enabled = true;

INSERT INTO etl_formula_help
    (function_name, category, syntax, summary, usage_text, examples_json, notice, sort_order)
VALUES
    ('abs', '수학 함수', 'abs(숫자)', '주어진 숫자의 절댓값을 반환합니다. 숫자가 아닌 값이 입력되면 빈 값을 반환합니다.', '숫자의 절댓값을 구할 때 사용합니다.',
     '[{"formula":"abs(-5)","description":"-5의 절댓값을 반환합니다.","result":"5"},{"formula":"abs(`value`)","description":"`value` 컬럼 값의 절댓값을 반환합니다.","result":"예) value 컬럼이 -30이면 30"}]',
     '인수는 숫자형으로 해석 가능해야 합니다.', 10),
    ('acos', '수학 함수', 'acos(숫자)', '주어진 값의 아크코사인(역삼각 함수)을 반환합니다. 입력 값이 -1에서 1 사이가 아니거나 숫자가 아니면 빈 값을 반환합니다.', '코사인 값으로 각도를 계산할 때 사용합니다.',
     '[{"formula":"acos(1)","description":"1의 아크코사인을 반환합니다.","result":"0"},{"formula":"acos(0)","description":"0의 아크코사인을 반환합니다.","result":"1.5707963267948966"}]',
     '반환 단위는 라디안입니다.', 20),
    ('and', '조건/논리 함수', 'and(조건1, 조건2, ...)', '모든 조건이 TRUE이면 TRUE를 반환하고, 하나라도 FALSE이면 FALSE를 반환합니다.', '여러 조건을 모두 만족해야 하는 판정식에 사용합니다.',
     '[{"formula":"and(amount > 0, status = ''Y'')","description":"금액이 0보다 크고 상태가 Y인지 확인합니다.","result":"TRUE 또는 FALSE"},{"formula":"and(true, false)","description":"두 번째 조건이 FALSE입니다.","result":"FALSE"}]',
     'NULL 조건은 Calcite SQL의 3값 논리 규칙을 따를 수 있으므로 COALESCE로 보정하는 것이 좋습니다.', 30),
    ('asin', '수학 함수', 'asin(숫자)', '주어진 값의 아크사인(역삼각 함수)을 반환합니다. 입력 값이 -1에서 1 사이가 아니거나 숫자가 아니면 빈 값을 반환합니다.', '사인 값으로 각도를 계산할 때 사용합니다.',
     '[{"formula":"asin(1)","description":"1의 아크사인을 반환합니다.","result":"1.5707963267948966"},{"formula":"asin(0)","description":"0의 아크사인을 반환합니다.","result":"0"}]',
     '반환 단위는 라디안입니다.', 40),
    ('atan', '수학 함수', 'atan(숫자)', '주어진 값의 아크탄젠트(역삼각 함수)를 반환합니다. 숫자가 아니면 빈 값을 반환합니다.', '탄젠트 값으로 각도를 계산할 때 사용합니다.',
     '[{"formula":"atan(1)","description":"1의 아크탄젠트를 반환합니다.","result":"0.7853981633974483"},{"formula":"atan(0)","description":"0의 아크탄젠트를 반환합니다.","result":"0"}]',
     '반환 단위는 라디안입니다.', 50),
    ('avg', '통계 함수', 'avg(숫자)', '입력 값의 평균을 반환합니다.', '그룹 또는 윈도우 기준의 평균값이 필요할 때 사용합니다.',
     '[{"formula":"avg(amount)","description":"amount 컬럼의 평균을 계산합니다.","result":"평균 숫자"},{"formula":"avg(case when amount > 0 then amount end)","description":"양수 금액만 평균에 포함합니다.","result":"조건 평균"}]',
     '집계 함수이므로 SELECT 범위와 GROUP BY 규칙을 함께 맞춰야 합니다.', 60),
    ('case', '조건/논리 함수', 'case when 조건 then 값 else 값 end', '조건에 따라 다른 값을 반환합니다.', '분기 로직이나 코드값 변환에 사용합니다.',
     '[{"formula":"case when grade = ''A'' then ''우수'' else ''일반'' end","description":"grade 값에 따라 라벨을 변환합니다.","result":"우수 또는 일반"},{"formula":"case when amount is null then 0 else amount end","description":"NULL 금액을 0으로 보정합니다.","result":"숫자"}]',
     'THEN과 ELSE의 반환 타입은 서로 호환되도록 작성해야 합니다.', 70),
    ('cast', '기타', 'cast(값 as 타입)', '값을 지정한 타입으로 변환합니다.', '문자, 숫자, 날짜 타입을 명시적으로 맞출 때 사용합니다.',
     '[{"formula":"cast(order_no as varchar)","description":"주문번호를 문자열로 변환합니다.","result":"문자열"},{"formula":"cast(amount as decimal(18,2))","description":"금액을 소수 타입으로 변환합니다.","result":"DECIMAL 값"}]',
     '변환할 수 없는 값은 실행 오류가 날 수 있으므로 원천 데이터 품질을 확인해야 합니다.', 80),
    ('ceil', '수학 함수', 'ceil(숫자)', '숫자보다 크거나 같은 가장 작은 정수를 반환합니다.', '소수 값을 올림 처리할 때 사용합니다.',
     '[{"formula":"ceil(12.31)","description":"12.31을 올림합니다.","result":"13"},{"formula":"ceil(price / 100)","description":"계산 결과를 올림합니다.","result":"정수"}]',
     '음수에서는 0에 가까운 방향이 아니라 수학적 올림 규칙을 따릅니다.', 90),
    ('char_length', '문자열 함수', 'char_length(문자열)', '문자열의 문자 수를 반환합니다.', '입력값 길이 검증이나 잘라내기 조건에 사용합니다.',
     '[{"formula":"char_length(''ABC'')","description":"ABC의 문자 수를 계산합니다.","result":"3"},{"formula":"char_length(customer_name)","description":"고객명 길이를 계산합니다.","result":"문자 수"}]',
     '바이트 길이가 아니라 문자 수 기준입니다.', 100),
    ('coalesce', '조건/논리 함수', 'coalesce(값1, 값2, ...)', 'NULL이 아닌 첫 번째 값을 반환합니다.', 'NULL 대체값을 지정할 때 사용합니다.',
     '[{"formula":"coalesce(phone, mobile, ''없음'')","description":"phone, mobile 순서로 첫 값을 선택합니다.","result":"전화번호 또는 없음"},{"formula":"coalesce(amount, 0)","description":"NULL 금액을 0으로 대체합니다.","result":"숫자"}]',
     '인수들의 타입이 서로 호환되어야 합니다.', 110),
    ('concat', '문자열 함수', 'concat(문자열1, 문자열2, ...)', '여러 문자열을 이어 붙입니다.', '코드 조합이나 표시용 문자열 생성에 사용합니다.',
     '[{"formula":"concat(first_name, '' '', last_name)","description":"이름과 성을 공백으로 연결합니다.","result":"전체 이름"},{"formula":"concat(''ORD-'', order_no)","description":"주문번호 앞에 접두어를 붙입니다.","result":"ORD-1001"}]',
     'NULL 처리 방식은 엔진 설정에 따라 달라질 수 있어 COALESCE와 함께 쓰면 안정적입니다.', 120),
    ('count', '통계 함수', 'count(값)', '행 개수 또는 NULL이 아닌 값의 개수를 반환합니다.', '집계 건수를 계산할 때 사용합니다.',
     '[{"formula":"count(*)","description":"전체 행 수를 계산합니다.","result":"행 수"},{"formula":"count(customer_id)","description":"customer_id가 NULL이 아닌 행 수를 계산합니다.","result":"개수"}]',
     '집계 함수이므로 GROUP BY 규칙을 함께 맞춰야 합니다.', 130),
    ('current_date', '날짜/시간 함수', 'current_date', '현재 날짜를 반환합니다.', '실행일 기준 조건이나 기본값에 사용합니다.',
     '[{"formula":"current_date","description":"오늘 날짜를 반환합니다.","result":"예) 2026-09-10"},{"formula":"order_date = current_date","description":"주문일이 오늘인지 비교합니다.","result":"TRUE 또는 FALSE"}]',
     '런타임 환경의 날짜 기준을 따릅니다.', 140),
    ('floor', '수학 함수', 'floor(숫자)', '숫자보다 작거나 같은 가장 큰 정수를 반환합니다.', '소수 값을 내림 처리할 때 사용합니다.',
     '[{"formula":"floor(12.91)","description":"12.91을 내림합니다.","result":"12"},{"formula":"floor(score / 10)","description":"구간 번호를 계산합니다.","result":"정수"}]',
     '음수에서는 0에서 멀어지는 방향으로 내려갈 수 있습니다.', 150),
    ('lower', '문자열 함수', 'lower(문자열)', '문자열을 소문자로 변환합니다.', '대소문자 차이를 없애고 비교할 때 사용합니다.',
     '[{"formula":"lower(''ABC'')","description":"ABC를 소문자로 변환합니다.","result":"abc"},{"formula":"lower(email)","description":"이메일을 소문자로 정규화합니다.","result":"소문자 이메일"}]',
     NULL, 160),
    ('max', '통계 함수', 'max(값)', '가장 큰 값을 반환합니다.', '최신일자, 최대 금액 등을 구할 때 사용합니다.',
     '[{"formula":"max(order_date)","description":"가장 늦은 주문일자를 구합니다.","result":"최신 날짜"},{"formula":"max(amount)","description":"최대 금액을 구합니다.","result":"숫자"}]',
     '집계 함수이므로 GROUP BY 규칙을 함께 맞춰야 합니다.', 170),
    ('min', '통계 함수', 'min(값)', '가장 작은 값을 반환합니다.', '최초일자, 최소 금액 등을 구할 때 사용합니다.',
     '[{"formula":"min(order_date)","description":"가장 이른 주문일자를 구합니다.","result":"최초 날짜"},{"formula":"min(amount)","description":"최소 금액을 구합니다.","result":"숫자"}]',
     '집계 함수이므로 GROUP BY 규칙을 함께 맞춰야 합니다.', 180),
    ('or', '조건/논리 함수', 'or(조건1, 조건2, ...)', '조건 중 하나라도 TRUE이면 TRUE를 반환합니다.', '여러 조건 중 하나만 만족해도 되는 판정식에 사용합니다.',
     '[{"formula":"or(status = ''A'', status = ''B'')","description":"상태가 A 또는 B인지 확인합니다.","result":"TRUE 또는 FALSE"},{"formula":"or(false, true)","description":"두 번째 조건이 TRUE입니다.","result":"TRUE"}]',
     'NULL 조건은 Calcite SQL의 3값 논리 규칙을 따를 수 있습니다.', 190),
    ('substring', '문자열 함수', 'substring(문자열 from 시작 for 길이)', '문자열의 일부를 반환합니다.', '코드의 앞자리나 날짜 문자열 일부를 추출할 때 사용합니다.',
     '[{"formula":"substring(''20260910'' from 1 for 4)","description":"연도 부분을 추출합니다.","result":"2026"},{"formula":"substring(product_code from 1 for 2)","description":"상품 코드 앞 2자리를 추출합니다.","result":"분류 코드"}]',
     '시작 위치는 1부터 계산합니다.', 200),
    ('sum', '통계 함수', 'sum(숫자)', '숫자 값의 합계를 반환합니다.', '금액이나 수량 합계를 계산할 때 사용합니다.',
     '[{"formula":"sum(amount)","description":"amount 컬럼의 합계를 계산합니다.","result":"합계"},{"formula":"sum(case when status = ''Y'' then amount else 0 end)","description":"조건에 맞는 금액만 합산합니다.","result":"조건 합계"}]',
     'NULL은 합계에서 제외됩니다.', 210),
    ('trim', '문자열 함수', 'trim(문자열)', '문자열 앞뒤의 공백을 제거합니다.', '입력값 정규화에 사용합니다.',
     '[{"formula":"trim('' ABC '')","description":"앞뒤 공백을 제거합니다.","result":"ABC"},{"formula":"trim(customer_name)","description":"고객명 앞뒤 공백을 제거합니다.","result":"정리된 고객명"}]',
     NULL, 220),
    ('upper', '문자열 함수', 'upper(문자열)', '문자열을 대문자로 변환합니다.', '코드값이나 식별자를 대문자로 정규화할 때 사용합니다.',
     '[{"formula":"upper(''abc'')","description":"abc를 대문자로 변환합니다.","result":"ABC"},{"formula":"upper(country_code)","description":"국가 코드를 대문자로 변환합니다.","result":"대문자 코드"}]',
     NULL, 230);
